.\" Manpage for elabctl.
.TH ELABCTL 1
.SH NAME
elabctl \- manage an eLabFTW installation
.SH SYNOPSIS
.B elabctl \fI[COMMAND]
.TP
.B elabctl \fIhelp
.SH DESCRIPTION
.B elabctl
allows you to install, backup, monitor and update easily eLabFTW.
.SH COMMANDS
.BR backup
Make a backup of your installation in /var/backups/elabftw.
.TP
.BR help
Display available commands
.TP
.BR install
Configure eLabFTW interactively. It will install Pip, a python package manager,
used to install docker-compose. It will also prepare the docker-compose
configuration file /etc/elabftw.yml and get the TLS certificates from
Let's Encrypt if possible.
.TP
.BR logs
Show logs of the mysql and eLabFTW containers
.TP
.BR php-logs
Show the last 15 lines of /var/log/nginx/error.log from the container
.TP
.BR restart
Restart the containers
.TP
.BR self-update
Fetch the latest version of the
.B elabctl
script and save it in /usr/bin.
.TP
.BR start
Start the containers
.TP
.BR status
Show status of running containers
.TP
.BR stop
Stop the containers
.TP
.BR uninstall
Remove all trace of eLabFTW on this system. Will delete the containers, the images, the config file, the man page, the data directory, the backup directory and the log file.
.TP
.BR update
Update to the latest version
.TP
.BR version
Display current version
.SH BUGS
The self-update command might display errors, but it works if you try again.
.SH AUTHOR
Nicolas CARPi (nicolas.carpi@curie.fr)

